### ISSUE TITLE
Handle merged and obsolete records

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-api#100]
**Describe the problem you would like to solve**
The first phase of development of ROR's independent curation infrastructure is limited to building functionality to add new records and update existing records. The first phase of work does not include functionality for merging, redirecting, and deprecating ROR IDs. ROR needs to support this functionality so that the registry provides an accurate reflection of a given organization's status in cases when organizations merge or shut down. 

**Describe the solution you'd like**
TBD - requires community input

**Who would benefit from this feature?**
All ROR users and stakeholders

**Additional information**

**Comment by lizkrznarich** [comment]
To be scoped further, with feedback from related issues:
https://github.com/ror-community/ror-api/issues/199
https://github.com/ror-community/ror-api/issues/99
