### ISSUE TITLE
Ampersands in organization names are problematic

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#122]
**Issue**: Ampersands in organization names are problematic when they are included in API queries. ROR API needs to be able to handle queries that include an ampersand. 

**Example 1**: https://ror.org/017xw6w34 is the ROR record for Abingdon and Witney College. The university uses an ampersand in its official name (see https://www.abingdon-witney.ac.uk/) so we expect that many users will search for the university using the ampersand in the name. 

If you query `api.ror.org/organizations?query=abingdon & witney` the API errors out (see screenshot) with the message `query parameter ' witney' is illegal`. A query for `abingdon and witney` does not return an error; it successfully returns the requested ROR. 

**Example 2**: https://ror.org/04fp4ps48 (Franklin & Marshall College). In this case, the ampersand actually appears in the ROR name. The same error happens if you query the API using the ampersand. 

**Required functionality**: Users need to be able to query the API with an ampersand in an organization name without getting an error. 

![Screen Shot 2020-10-28 at 9 35 44 AM](https://user-images.githubusercontent.com/45110557/97444175-3aad5880-1902-11eb-9562-f83307f2d4da.png)

**Comment by ritikbhatia** [comment]
@mariagould to make it work, the ampersand should be encoded to `%26` before passing it as a URL parameter as follows:
https://api.ror.org/organizations?query=abingdon%20%26%20witney

**Comment by lizkrznarich** [comment]
No dev work needed - & chars should be URL encoded to prevent being interpreted as parameters. UI already does this automatically. Updated docs to add example https://ror.readme.io/docs/rest-api#special-characters
