### ISSUE TITLE
Affiliation matching failing test

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-api#126]
On the branch where all the metadata is being brought in, the affiliation match test fails at the following affiliation string. I am outputting the status code, error traceback, and the string:
```
query:  Department of Oriental Rehabilitation, Kangnam Korean Hospital, Kyung Hee University, Seoul, Korea.
status code:  500
ERROR

======================================================================
ERROR: test_matching (rorapi.tests_functional.tests_matching.AffiliationMatchingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/app/webapp/rorapi/tests_functional/tests_matching.py", line 39, in setUp
    self.results.append(self.match(d['affiliation']))
  File "/home/app/webapp/rorapi/tests_functional/tests_matching.py", line 25, in match
    'affiliation': affiliation
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------
Ran 1 test in 181.989s
```
When I run this query, `http://localhost:9292/organizations?affiliation=Department%20of%20Oriental%20Rehabilitation,%20Kangnam%20Korean%20Hospital,%20Kyung%20Hee%20University,%20Seoul,%20Korea` in the browser, I get the following error:
```
AttributeError at /organizations
Got AttributeError when attempting to get a value for field `id` on serializer `GeoNamesCitySerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `AttrDict` instance.
Original exception text was: 'AttrDict' object has no attribute 'id'.
```

Other affiliation queries work, for ex: `http://localhost:9292/organizations?affiliation=Department%20of%20Clinical%20Research,%20Venous%20Research%20Foundation,%20Chicago,%20Illinois,%20USA`.

To run this in the branch, please switch over to the branch `feature/all_grid` locally and run the following:
`docker-compose up -d`
`docker-compose exec web python manage.py setup`
`docker-compose exec web python manage.py test rorapi.tests_functional.tests_matching.AffiliationMatchingTestCase.test_matching -v 2`

**Comment by dtkaczyk** [comment]
@eshadatta-crossref I fixed the modelling of matching results and updated the test data for one test. All tests seem to pass now. The commits are in the branch.

**Comment by eshadatta-crossref** [comment]
Awesome, thanks @dtkaczyk!
