### ISSUE TITLE
Consider if we need to re-enable cloudfront for API

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#128]
We deactivated Cloudfront for the API during the Terraform cutover and it remains inactive. We need to determine whether or not to re-enable Cloudfront. 

Reasons to re-enable:
- When we add new data to the ROR API it might take a little time for us to see it
- Support better performance

Reasons not to re-enable:
- It might make it easier to deploy new API versions (avoids Cloudfront invalidations)
- Performance might be good enough without it

**Comment by mfenner** [comment]
I am not sure I understand reasons to re-enable #1. Reason #2 is a potentially useful, but we have not measured the impact, and that is also not trivial to do.

**Comment by mariagould** [comment]
We have decided that we will not need Cloudfront enabled for ror-api (we will continue using it for the homepage).
