### ISSUE TITLE
Research: Prepare metadata for ROR

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#140]
To input changes in ROR once request is approved, metadata needs to be prepared by curator(s). We need to research and plan the best way to set this up.

**Comment by mariagould** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare metadata record](https://trello.com/c/zobEgNRf/25-prepare-metadata-record)

**Comment by mariagould** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prepare batch for ROR update](https://trello.com/c/X01Ptstx/52-prepare-batch-for-ror-update)

**Comment by eshadatta-crossref** [comment]
https://github.com/ror-community/ror-records/blob/v.1.2.9-rc/t.json
