### ISSUE TITLE
Automatically send new ROR data dump to Zenodo

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#143]
Zenodo-Github integration: https://zenodo.org/account/settings/github/

1. Select repository
2. Tag release
3. Zenodo will automatically download a .zip-ball of each new release and register a DOI
![Screen Shot 2021-02-05 at 3 01 34 PM](https://user-images.githubusercontent.com/45110557/107098000-0bd93500-67c3-11eb-915e-21a264856ca8.png)

**Comment by lizkrznarich** [comment]
Action: https://github.com/ror-community/ror-records/pull/61
Script: https://github.com/ror-community/curation_ops/pull/17
