### ISSUE TITLE
Refinements to affiliation matching

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#153]
Setting up this ticket to capture proposed enhancements to the affiliation matching function.

**Comment by lizkrznarich** [comment]
From Ivo at OA Switchboard: 
We would only be interested in those score 1.0 cases and we don’t need the other 15 results J. It will only slow things down. So maybe add an extra argument scoreminimum and let the endpoint return only perfect scores?

Note from Liz: Could also add filter for "chosen" field

**Comment by lizkrznarich** [comment]
From multiple users:
Reduce minimum character threshold required to return results (currently 12; suggested value is 6-8)

**Comment by mariagould** [comment]
Closing as duplicate of #196
