### ISSUE TITLE
Index external ID as a search parameter

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#155]
As a user, I want to look up an organization in ROR using a non-ROR ID so that I can efficiently map affiliation data from one type of ID to the other.

**Comment by hauschke** [comment]
Is there any plan to implement this soon?

**Comment by lizkrznarich** [comment]
@hauschke @mariagould Can speak further to implementation plans, but at the moment, a workaround is using quotes to return exact matches for other ID types, ex ```curl https://api.ror.org/organizations?query=%22grid.14003.36%22 ``` . This still searches the entire ROR record, however, in practice, other organization ID types currently only appear in the external_ids section of a record. I will be posting a code example that takes a list of other IDs as a CSV and returns corresponding ROR IDs using this approach soon.

**Comment by mariagould** [comment]
Hi @hauschke this is not on the near-term horizon for implementation as we are focused on other priorities but the workaround that @lizkrznarich recommends would be a great place to start. Please feel free to share more information about your needs and use cases so we can take this into account in future development planning.
