### ISSUE TITLE
Investigate migration path and implications for upgrading ES from 6.x to 7.x

### ISSUE THREAD

**Issue by eshadatta-crossref** [ror-community/ror-api#167]
The ES version for the ror-api is at 6.2.3. Elasticsearch is currently at 7.9, so we need to look at the migration of ES to a later version. Other dependencies include implications of the upgrade on the index schema(including aggregations) and the application.

**Comment by eshadatta-crossref** [comment]
@mfenner will look into the upgrade path for ES 6.x to 7.x as well as implications on the schema and the aggregations. @eshadatta-crossref will look at the application behavior with the upgrade.

**Comment by lizkrznarich** [comment]
A issue to keep an eye on is that AWS has changed its Elasticsearch service to Opensearch as of 1 Sep 2021 https://docs.aws.amazon.com/opensearch-service/latest/developerguide/rename.html#rename-nochange . At the moment, Opensearch still supports ES, but Opensearch is a fork of Elasticsearch and will likely diverge over time.

**Comment by lizkrznarich** [comment]
Completed as part of https://github.com/ror-community/ror-roadmap/issues/161
