### ISSUE TITLE
Include created/last modified dates in ROR records

### ISSUE THREAD

**Issue by lizkrznarich** [ror-community/ror-api#183]
In order to make the process as efficient as possible for those regularly consuming/ingesting ROR records, created and last modified dates should be included.

This will allow integrators to:

- Regularly ingest new/modified records rather than the entire ROR dataset
- Identify record changes that may impact their systems

**Comment by icraig-afk** [comment]
@mariagould 
Hi Maria, is there any workaround to be able to find just the records that are new or have changed? Or do we need to wait for https://github.com/ror-community/ror-roadmap/issues/9 to complete? Thanks, Iain

**Comment by lizkrznarich** [comment]
Hi @icraig-afk There's not a great way to do this within the API at the moment, however, there are 2 possible workarounds:
- New and updated records IDs are listed in the release notes here https://github.com/ror-community/ror-updates/releases/tag/v1.0 . You can get releases from Github with ```curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/ror-community/ror-updates/releases``` and check the ```body``` field of the latest release. Not nice to parse, but doable since the full ROR IDs are there in a consistent format.
- In the [data dump](https://doi.org/10.5281/zenodo.6347575), new/updated records are appended to the end of the JSON file, so you could check the previous dump to see what the last record is and go from there. Caveat: updated records jump to the bottom of the file, so you can't determine where new records begin based on the number of lines in a previous dump (and anyway, updated records often have additional lines). Also, if the last record in a previous dump was updated in the current dump, that record will be in a different position, so it won't serve as a useful marker.

**Comment by arthurpsmith** [comment]
Yes, this would be very useful. With GRID my technique for filtering out just new records was by noticing that the numeric parts of GRID id's were gradually increasing, but ROR id's are much more  random so there's no such heuristic available there!
