### ISSUE TITLE
API search issues & suggested improvements

### ISSUE THREAD

**Issue by lizkrznarich** [ror-community/ror-api#196]
Use this issue for documenting cases where ROR API search (either ?query or ?affiliation parameter) doesn't work well. 

In your comment, please include:
- Examples of unsuccessful queries
- Your use case (ex: a typeahead widget in a web form, a script matching organization names to ROR IDs, etc)
- (optionally) Your suggestions for improvements

**Comment by lizkrznarich** [comment]
Reported by OA Switchboard developers

Example:
https://api.ror.org/organizations?page=1&affiliation=1st%20Division%20of%20Infectious%20Diseases%2C%20%26%23x201C%3BLuigi%20Sacco%26%23x201D%3B%20University%20Hospital

Use case: 
Script matching affiliations to ROR IDs using ?affiliation search

Issue:
Returns non-relevant result Universitätsklinikum Erlangen as a match with chosen = true based on "score" : 1, "substring" : "University Hospital".

Possible improvements:
- Remove substrings composed of only very common terms (this has drawbacks in the case of institutions like University College)
- Remove additional "University" search variations
- De-prioritize (or strip, in some cases) common terms like University (again, this creates issues for names like University College)
- Remove single and double quotes from strings passed to ?affiliation (they are parsed as literals)

**Comment by lizkrznarich** [comment]
Additional suggestions, including fielded search, based on https://docs.google.com/document/d/1cTf6OBjgHfmij1kgMXKgPon1codmTBl4F1PmmXnFYlU/edit#heading=h.udv4m4xie6mv

**Comment by mariagould** [comment]
Moving these comments from #153 

From Ivo at OA Switchboard:
We would only be interested in those score 1.0 cases and we don’t need the other 15 results J. It will only slow things down. So maybe add an extra argument score minimum and let the endpoint return only perfect scores?

Note from Liz: Could also add filter for "chosen" field

From multiple users:
Reduce minimum character threshold required to return results (currently 12; suggested value is 6-8)

**Comment by lizkrznarich** [comment]
Searching "Donbas State Pedagogical University" fails to return https://ror.org/059mp4e63 "Donbass State Pedagogical University,' which is an incorrect spelling

**Comment by lizkrznarich** [comment]
Hi @nsherzog the default ?query param search is sort of a "quick search" that only searches name, aliases, labels acronyms and external identifiers, so this is actually the expected behavior. To search based on city or other location info, use the newly-added [advanced search functionality](https://ror.readme.io/docs/advanced-search) available via ?query.advanced, ex:

```https://api.ror.org/organizations?query.advanced=addresses.geonames_city.city%3AWarsaw+AND+%28types%3AEducation+OR+types%3ACompany%29```
More info on the different search approaches ROR offers and what they do is here https://ror.readme.io/docs/rest-api#search-ror-records

Also, a note on filters: Filters are subtractive rather than additive, meaning that using both types:Education and types:Company reduces the result set to only records that have both types, not records that have either Education or Company. In this case, I'd suggest using fielded search to retrieve records with a type of either Education or Company.

**Comment by amandafrench** [comment]
Beta testing issue with [new ?affiliation matching](https://github.com/ror-community/ror-roadmap/discussions/77), reported by Beilstein Institut when searching for "Institute of Macromolecular Chemistry, Academy of Sciences of the Czech Republic, Heyrovského nám. 2, 162 06 Prague 6, Czech Republic". 

Current production search returns 22 results with expected result, https://ror.org/0143w7709, as chosen = true with a score of .94: 

https://api.ror.org/organizations?affiliation=Institute%20of%20Macromolecular%20Chemistry%2C%20Academy%20of%20Sciences%20of%20the%20Czech%20Republic%2C%20Heyrovsk%C3%A9ho%20n%C3%A1m.%202%2C%20162%2006%20Prague%206%2C%20Czech%20Republic 

Beta search returns 10 results, none of which are chosen = true, with expected result https://ror.org/0143w7709 having a matching score of .74 (PHRASE match on "Institute of Macromolecular Chemistry")

**Comment by lizkrznarich** [comment]
Thanks to all those who commented here for your feedback! Improvements to affiliation matching have now been deployed to production after 2 months of testing in our staging env - see release notes here https://ror.readme.io/changelog/2022-10-24-affiliation-matching-improvements-api-only . This is an incremental improvement; we may revisit with a larger re-work in the future, so please continue to let us know of any issues you find.
