### ISSUE TITLE
Empty search results when query.name contains "noise" terms

### ISSUE THREAD

**Issue by dtkaczyk** [ror-community/ror-api#21]
When query.name contains additional "noise" terms, the result list is empty. For example, `https://api.ror.org/organizations?query.name=university+warsaw` returns 12 items, but `https://api.ror.org/organizations?query.name=university+warsaw+anything` returns an empty list.

It does affect the search box at ror.org as well.

It doesn't happen if "query" parameter is used instead.

**Comment by mariagould** [comment]
@dtkaczyk can I close this because I think we are addressing the issue via #54 ?

**Comment by dtkaczyk** [comment]
I would wait for merging to production. Currently it is in dev only.
