### ISSUE TITLE
Properly handle ISNI identifiers

### ISSUE THREAD

**Issue by mfenner** [ror-community/ror-api#22]
They can optionally contain spaces or hyphens. The link to Open ISNI requires an identifier without any hyphens or spaces.

Ideally this is fixed on import, and the ISNI is standardized to use hyphens.

**Comment by arthurpsmith** [comment]
Actually ISNI has fixed this now - at least for identifiers with spaces, it now works. Try http://www.isni.org/0000+0001+2341+2786
for example.

**Comment by mfenner** [comment]
Great! That will help with our implementation.

**Comment by mariagould** [comment]
Related to #173 as we are proposing formatting all external IDs as URLs in the API. Also related to https://github.com/ror-community/ror-app/issues/43 as we need to determine if we should make any formatting changes to the way in which external IDs are displayed in the search UI.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-app/pull/102
