### ISSUE TITLE
Support for unstructured affiliations and multiple affiliations

### ISSUE THREAD

**Issue by de-code** [ror-community/ror-api#23]
Searching for `Department of Biology, ETH Zurich, 8092 Zurich, Switzerland.` currently returns no results.
It is only matching the entry for `ETH Zurich`.

Some records are ambiguous when not taking the location into account.

It would be good if the API was able to handle an unstructured text that may contain multiple affiliations. The API should then return what portion of the text it matched. It should extract the location from the text and consider it for matching but also mark as matched in the response.

Would that be in scope of the project?

**Comment by dtkaczyk** [comment]
@de-code The support for affiliation matching was recently added to the API. You can use it like this:

```
https://api.ror.org/organizations?affiliation=Department%20of%20Biology,%20ETH%20Zurich,%208092%20Zurich,%20Switzerland
```

More information about this functionality can be found in [README](https://github.com/ror-community/ror-api/blob/master/README.md#affiliation-matching).
