### ISSUE TITLE
Affiliation search errors

### ISSUE THREAD

**Issue by Goldensteev** [ror-community/ror-api#246]
I have started using ROR.org to parse through a list of affiliations and try to find relevant structures in said affiliations.
For the most part we have good results, but there are as expected some errors. 
Here is an example of one such error.

Doing a search for a simple french affiliation : "CHU Rennes"
```python
requests.get("https://api.ror.org/organizations?affiliation=CHU%20Rennes")
```
results in
```
CHU False 0.9 ACRONYM Colorado Heights University
CHU False 0.9 ACRONYM Chiba University Hospital
CHU False 0.9 ACRONYM Centre Hospitalier Universitaire de Nancy
CHU False 0.9 ACRONYM Centre Hospitalier Universitaire de Bordeaux
CHU False 0.9 ACRONYM Centre Hospitalier et Universitaire de Brazzaville
CHU True 0.9 ACRONYM Centre Hospitalier Universitaire de Caen
CHU False 0.9 ACRONYM University Teaching Hospital of Yaounde
CHU False 0.9 ACRONYM University Hospital Medical Center at Treichville
CHU False 0.9 ACRONYM Centre Hospitalier Universitaire de Nantes
CHU False 0.9 ACRONYM Centre Hospitalo-Universitaire Bab El Oued
```
These results are all incorrect and i expect in the list of results [Centre Hospitalier Universitaire de Rennes](https://ror.org/05qec5a53), which is the correct answer. I find it odd that the only search that is done is an ACRONYM search, seeing as the key part of this specific affiliation is the location - Rennes.

Thanks

**Comment by amandafrench** [comment]
Thanks for this report, @Goldensteev. We're tracking similar issues in #196, and this will be helpful.

Affiliation searches [search only the name-related fields](https://ror.readme.io/docs/rest-api#affiliation-parameter), not locations, so the search was only looking for "Rennes" in `name,` `label,` and `alias`. But the main reason [Centre Hospitalier Universitaire de Rennes](https://ror.org/05qec5a53) wasn't returned is that the record doesn't have "CHU" in its `acronym` field or in any of the other name-related fields targeted by an affiliation search, so I'll submit a request to have that added and link it here. 

The current record does have an alias of "CHU de Rennes," so the following search would produce the result you're looking for:

```requests.get("https://api.ror.org/organizations?affiliation=CHU%20de%20Rennes")``` 

I see why you'd expect CHU de Rennes to be returned in that search, though, and we are looking at ways to improve searching in general, so again, thanks for the issue report.

**Comment by amandafrench** [comment]
Here's the issue requesting "CHU" be added as an acronym for https://ror.org/05qec5a53 -- https://github.com/ror-community/ror-updates/issues/829

**Comment by Goldensteev** [comment]
Thank you for the answer!

Here is another example of an affiliation with multiple errors:

> CIC Bordeaux CIC1401, Bordeaux, France ADERA, Pessac, France.

![image](https://user-images.githubusercontent.com/14848329/177729551-8aa51ffc-393c-4b54-9ffc-dbad6b058a9d.png)

this aff has 2 orgs :
- CIC Bordeaux CIC1401 which doens't exist in the ROR Db and i have submitted the change
- [ADERA](https://ror.org/04r2r8477), which is too low down the list IMO

**Comment by amandafrench** [comment]
Hi @Goldensteev -- thought you might be interested in trying out some changes weave made to ?affiliation matching. Your examples work much better in the beta we've put on staging. See announcement here: https://github.com/ror-community/ror-roadmap/discussions/77

**Comment by Goldensteev** [comment]
Thanks @amandafrench ill have another go at it. We have a pretty big list of affiliations we are parsing and we haven't done a full look into all the potential errors but if i have time ill try and submit a few here.

**Comment by lizkrznarich** [comment]
@Goldensteev The improvements mentioned above have now been deployed to production - see release notes here https://ror.readme.io/changelog/2022-10-24-affiliation-matching-improvements-api-only . This is an incremental improvement; we may revisit with a larger re-work in the future, so please continue to let us know of any issues you find.
