### ISSUE TITLE
lnwiptv Thailand's state metrology organization and contributor to BIPM. Independent, top-level entity that funds and employs researchers. In scope per our addition of other state metrology orgs. Should be added to ROR.

### ISSUE THREAD

**Issue by proseoads** [ror-community/ror-api#262]
Thailand's state metrology organization and contributor to BIPM. Independent, top-level entity that funds and employs researchers. In scope per our addition of other state metrology orgs. Should be added to ROR.

Publication affiliation usage: https://link.springer.com/article/10.1007/s12647-022-00552-7 ; https://iopscience.iop.org/article/10.1088/0026-1394/58/1A/04003/meta ; https://iopscience.iop.org/article/10.1088/1681-7575/ab64a9/meta

Google Scholar affiliation usage: https://scholar.google.com/citations?user=bRu9mhEAAAAJ; https://scholar.google.com/citations?user=Mzvrr0gAAAAJ; https://scholar.google.com/citations?user=dVaoeW0AAAAJ

ORCID affiliation usage:https://orcid.org/0000-0003-4004-5708

_Originally posted by @adambuttrick in https://github.com/ror-community/ror-updates/issues/875#issuecomment-1187704858_

**Comment by lizkrznarich** [comment]
@proseoads A record has already been created for this organization https://ror.org/01357ty92 . This repository contains API code only; curation requests are not handled here. All curation requests are handled through the request process in https://github.com/ror-community/ror-updates#requesting-changes-to-ror.
