### ISSUE TITLE
Identify inactive GRID records in ROR

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#44]
We need to be able to identify records in ROR that have been marked as inactive in GRID. We want mark these records with a different status as opposed to suppressing them entirely.

**Comment by mariagould** [comment]
This is related to #43

**Comment by mariagould** [comment]
@gbilder @mfenner @dtkaczyk do we still need to get some examples from GRID to use for testing?

**Comment by arthurpsmith** [comment]
Ah that's interesting - this is actually causing trouble for ROR now - see:
   https://ror.org/024h8a058
which was based on grid.491703.8 - which was in a previous release a company "AO" from Bergheim, Germany, but is now marked obsolete in the GRID json file.

So - don't lose the old ROR metadata if GRID removes its metadata for an entry?

A different example is grid.498773.6 which was redirected (merged) to grid.422522.1 - at least in that case I don't think there was a separate ROR id for the first one so it should be fine. But some of those redirects may be more of a problem.

**Comment by mariagould** [comment]
Thanks for these examples, Arthur. I agree with you about keeping the metadata when a record becomes obsolete. I think the idea would be to simply change the status of the record. 

For the merged/redirected records, the draft policy doc that we've been working on proposes keeping the original ROR IDs for the previous records and creating a new ID for the merged organization. Do you think that seems like a good approach?

**Comment by mariagould** [comment]
Working on this via #43
