### ISSUE TITLE
ROR ID URLs are not resolving

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#45]
Clicking a ROR ID URL or copy/pasting it into a web browser results in a blank page. Example: https://ror.org/0406jsq08.

**Comment by mfenner** [comment]
The underlying issue is that the API doesn't recognize https://api.ror.org/organizations/ror.org/03b9snr86. @dtkaczyk what am I missing?

**Comment by mfenner** [comment]
Closed via #46.
