### ISSUE TITLE
Import remaining GRID metadata not already in ROR

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#59]
I believe these are the fields that were not previously included. We need to confirm what field labels we want to use.

- Established

- Preferred ID

- Child Institutes

- Related Institutes

- City

- Admin Region (1, 2, etc.)

**Comment by sharifX** [comment]
Hi, will ROR include the relationships data (for example Parent Institutes) from GRID? I am looking for a way to grab Facility (for example labs) information that is a unit of another organisation.

**Comment by mariagould** [comment]
Hi @sharifX - ROR will include the relationships data (both parent institutes and related institutes) from GRID. The implementation work to incorporate this metadata is still in progress.

**Comment by mariagould** [comment]
Closing this as we have broken out this task into separate issues (e.g., #97 )
