### ISSUE TITLE
Slashes in a name make ROR api get 500 errors

### ISSUE THREAD

**Issue by sfisher** [ror-community/ror-api#61]
Try a query like this one and ROR has problems.  :-) 

https://api.ror.org/organizations?query=INFOTEC+Research+Inc.%2FApplied+Earthworks%2C+Inc.

Not a big deal and maybe it's just the query syntax/language.

**Comment by lizkrznarich** [comment]
@sfisher Sorry for the long delay on this! / is a reserved character in Elasticsearch query string syntax, so it needs to be escaped with a URL-encoded \ , ex: `https://api.ror.org/organizations?query=INFOTEC+Research+Inc.%5C%2FApplied+Earthworks%2C+Inc.` I've added some examples to our docs about special chars https://ror.readme.io/docs/rest-api#special-characters and we will update the UI search to escape Elasticsearch reserved chars automatically.

**Comment by lizkrznarich** [comment]
https://github.com/ror-community/ror-app/pull/64
