### ISSUE TITLE
extraneous leading tab and space character

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-api#81]
ror-2019-12-18 (should be 19) 2 months old

The ISNI data field for:

South Western Sydney Local Health District	"https://www.swslhd.nsw.gov.au/"
"https://ror.org/05j37e495"
grid.410692.8
"\t 0000 0001 2105 7653"

has an extraneous leading tab and space character	

correct to
"0000 0001 2105 7653"

**Comment by mariagould** [comment]
This issue has been fixed via the ROR curation process (https://github.com/ror-community/ror-updates/). Closing.
