### ISSUE TITLE
Name field appears to be badly formed

### ISSUE THREAD

**Issue by leonardcj** [ror-community/ror-api#83]
The Name line for:

University of Galati
"http://www.ugal.ro/"
"https://ror.org/052sta926"
grid.8578.2
"0000 0001 1012 534X"

appears to be badly formed, extraneous double quote character(s)?

"name": "\"Dunarea de Jos\" University of Galati",

**Comment by leonardcj** [comment]
in ror-2019-12-18 (should be 19) 2 months old

**Comment by mariagould** [comment]
@leonardcj I believe the current formatting follows how the university name is represented on its website http://www.ugal.ro/. There are double quotes because "Dunarea de Jos" appears in quotes in the name. I'm going to close this but feel free to follow up if I've missed something.
