### ISSUE TITLE
Python scripts documentation 

### ISSUE THREAD

**Issue by mariagould** [ror-community/ror-api#88]
Need documentation for scripts in https://github.com/ror-community/ror-api/tree/master/rorapi/management/commands

**Comment by mfenner** [comment]
This has been addressed in https://github.com/ror-community/ror-api/commit/498cd7e5f6fd9fca755f5e1892baf9c701ab0bd6 and https://github.com/ror-community/ror-api/commit/dea1f1d3492258d5d17e798511e4c49a1f1bc62a.

**Comment by mariagould** [comment]
Thanks @mfenner I see the setup documented but do you also have documentation for the scripts themselves?
